name = "PXDesign"
uuid = "491fc0bf-5d1a-4566-991e-f8dec03b0b2e"
authors = ["murrellb <murrellb@gmail.com>"]
version = "0.1.0"

[deps]
ConcreteStructs = "2569d6c7-a4a2-43d3-a901-331e8e4be471"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
ESMFold = "992ade7d-a23b-44e1-bfa9-f18d3a6e7567"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
NNlib = "872c559c-99b0-510c-b3b7-b6c96a88d5cd"
ONIONop = "021020d5-7125-488f-a684-9e3366e41e56"
Onion = "fdebf6c2-71da-43a1-b539-c3bc3e09c5c6"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProtInterop = "b3e4c6a1-2f5a-4d8c-9e7b-1a3c5d9f0e2b"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
SafeTensors = "eeda0dda-7046-4914-a807-2495fc7abb89"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[weakdeps]
MoleculeFlow = "0907176b-47b3-4e96-be91-0e9bb91fb14f"

[extensions]
PXDesignMoleculeFlowExt = "MoleculeFlow"

[compat]
ESMFold = "1.0.0"
NNlib = "0.9.33"
Onion = "0.2.18"
YAML = "0.4.16"
